### ISSUE TITLE
Ghost ping 

### ISSUE THREAD

**Issue by ethanlchristensen** [nulzo/DiscordBot#17]
Just realized ghost ping didn’t make it through the refactor. If you still want ghost ping, add it in FortniteBallsClient.py

**Comment by nulzo** [comment]
I'll update and make pr. Thanks, Ethan!

**Comment by ethanlchristensen** [comment]
@nulzo don't forget to pull the most recent changes . . . 
![image](https://user-images.githubusercontent.com/55725575/221014261-7c190a64-9e3a-4cfc-8969-b568f884bbd3.png)

**Comment by ethanlchristensen** [comment]
solved
