### ISSUE TITLE
bruhpy bug 

### ISSUE THREAD

**Issue by ethanlchristensen** [nulzo/DiscordBot#31]
bug with bruhpy when the '&' character is present in the code. perhaps a problem with the `base_process()` command.

Another bug is when # is used within f-strings instead of '\n'. While convention for bruhpy is to use # for '\n', if you must use a '\n' within a string or f-string, it should be written as '\n' and not #

thnx :) ~ will fix later aligator

**Comment by nulzo** [comment]
Update?

**Comment by ethanlchristensen** [comment]
@nulzo , the `&` part is not patched. The other isn't a bug, but rather when users want a new line in the string they use, they should use the `\n` instead of `#` with strings specifically. Cheers, mate!

**Comment by nulzo** [comment]
@ethanlchristensen Thank you kindly for your update. Look forward to future interactions ~ cheers

**Comment by ethanlchristensen** [comment]
`/bruh bruhpy for i in range(10):#\tprint("hello\nworld!")`

**Comment by ethanlchristensen** [comment]
bruhpy now makes use of the new bruh command that only allows for single command execution, `&` is no longer an issue
