### ISSUE TITLE
FB Parser

### ISSUE THREAD

**Issue by ethanlchristensen** [nulzo/DiscordBot#4]
The current "fortniteballs" utterance checker does not catch every possible instance of the saying

**Comment by Mr-Oregano** [comment]
the balls?????

**Comment by ethanlchristensen** [comment]
Hey, @Mr-Oregano  great to hear from you, Mr-Oregano! Not sure what you are asking here? Could you kindly clarify?

**Comment by Mr-Oregano** [comment]
@ethanlchristensen deez nuts in ur mouth
![image](https://user-images.githubusercontent.com/33503562/219151987-a482230f-4493-46e1-9de3-3220422bb6dc.png)
![image](https://user-images.githubusercontent.com/33503562/219152157-45273018-430a-4c59-9255-45bfce83c32e.png)

**Comment by ethanlchristensen** [comment]
@Mr-Oregano Thank you kindly for the clarification! 

![image](https://cdn.discordapp.com/attachments/746957590457483345/1075518752046727238/GOL.png)

**Comment by nulzo** [comment]
bro is really trying to say "fo69rtn123it420eba69ll(&:$/$(&:s" is a valid string... get out of here!

**Comment by ethanlchristensen** [comment]
hahahahhhaah, very funny @nulzo, it is a valid string, no?

**Comment by nulzo** [comment]
no. it's not. @ethanlchristensen

**Comment by ethanlchristensen** [comment]
Sounds good partner!
