### ISSUE TITLE
Capitalization issues with GOL

### ISSUE THREAD

**Issue by nulzo** [nulzo/DiscordBot#43]
GOL interpolation user-input is case-sensitive.

**Comment by Mr-Oregano** [comment]
honestly dude doesn't even know how to code

**Comment by ethanlchristensen** [comment]
erm

**Comment by ethanlchristensen** [comment]
@nulzo 
![image](https://user-images.githubusercontent.com/55725575/227341436-2a83f3c9-c264-42a3-a8a6-66e2ae3184e1.png)
As you can see some of the color maps have capital letters! not as simple as `.lower()`. luckily I am a genius engineer!

**Comment by ethanlchristensen** [comment]
@Mr-Oregano also cause of the comment you made!
![image](https://user-images.githubusercontent.com/55725575/227341830-6641a513-61eb-4480-8cf1-c85878dc1c0d.png)

**Comment by nulzo** [comment]
@ethanlchristensen well that's just an L on the part of the developers for matplotlib!
