### ISSUE TITLE
Nowplaying command needs to be improved

### ISSUE THREAD

**Issue by nulzo** [nulzo/DiscordBot#50]
The `\playing` command is intended to display what song is currently playing, and what channel the song is playing in. This command currently only shows what channel the song is playing in - not the song title. Improvements to this command are needed in order to ensure that the command retains its initial requirements.

**Comment by ethanlchristensen** [comment]
" . . . retains its initial requirements." @nulzo

**Comment by ethanlchristensen** [comment]
https://github.com/FNBBDevs/DiscordBot/pull/87/commits/37b0f7bb95646430b37acb88eaaa498ff9193c6f
