### ISSUE TITLE
FFMPEG dropping socket

### ISSUE THREAD

**Issue by nulzo** [nulzo/DiscordBot#70]
On extended videos ( > 1hr ) FFMPEG will disconnect and lose the socket it was using to attach to the VC. Looks like it could be a problem with asyncio timeouts

**Comment by nulzo** [comment]
Also worth noting that once this connection is severed it will fool the bot into thinking it is not in a voice channel even though it is in one

**Comment by ethanlchristensen** [comment]
LOL

**Comment by nulzo** [comment]
Fixed

**Comment by ethanlchristensen** [comment]
Guess I'll close my branch and stop working on this issue, thanks for the update!
