### ISSUE TITLE
IndexError: string index out of range (for embed message)

### ISSUE THREAD

**Issue by Mr-Oregano** [nulzo/DiscordBot#9]
Currently, receiving an embed message from another discord bot causes and index out of range error 

```
Message from Grow a Tree#5130: 
2023-02-15 16:38:17 ERROR  mdiscord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Spice\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event    
    await coro(*args, **kwargs)
  File "C:\Users\Spice\Dev\Code-Workspace\Fortnite-Balls-Discord-Bot\BOT\FortniteBallsBot.py", line 64, in on_message
    if message.content[0] == COMMAND_PREFIX:
IndexError: string index out of range
```

**Comment by nulzo** [comment]
just put it in a try-except block.. gg ez try harder next time

**Comment by Mr-Oregano** [comment]
> just put it in a try-except block.. gg ez try harder next time

absolutely not what are you thinking DO IT PROPERLY!!! 😡

**Comment by nulzo** [comment]
get good kid, try to keep up

**Comment by ethanlchristensen** [comment]
some errors are okay Onion Powder!! (@Mr-Oregano )

**Comment by Mr-Oregano** [comment]
> some errors are okay Onion Powder!! (@Mr-Oregano )

This one is not, do better

**Comment by ethanlchristensen** [comment]
@Mr-Oregano @nulzo let's just use `try` and `except` ! I will close this issue :D
![image](https://cdn.discordapp.com/attachments/1069835760859107371/1075606124436410444/A0E2AEF0-F05E-49F2-A0CD-BE8F967452FA.jpg)

**Comment by ethanlchristensen** [comment]
This issue will be solved with try and except, and a default response sent back!
